# **SPIRATEC CUMMINS FILTERS**: Second Analysis

### **Author**: PhD Daniel Diaz-Almeida

#### **Task 2**: _To determine the feasibility to stablish a correlation between measured vital signs and metal values_

## Introduction

In this report, a dataset of different measurements of the Spiratec Filters has been assessed.

The porpuse of this analysis has been to determine the feasibility to stablish a relationship between measured vital signs and metal values (in ppm). In order to perform the assessment, the data was imported from a *.csv file into a DataFrame which had more han 1.2MM rows (observations) and 74 attributes ranging from the adquisition date to the escape gas tempeture (EGT).

The data presents a good distribution and good enough observations to perform an estimation 

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('bmh')

In [2]:
# Bokeh Visualization

from bokeh.io import output_notebook, show
output_notebook()

Loading BokehJS ...

In [3]:
from bokeh.layouts import column, row
from bokeh.models import Select
from bokeh.palettes import Spectral5
from bokeh.plotting import curdoc, figure

In [4]:
file = "combinedFilters_csv.csv"
%time filt_df = pd.read_csv(file, delimiter=',')
filt_df.shape

Wall time: 7.37 s


(1295116, 74)

In [10]:
newcols = {"ESN":"ESN",
           "AVL":"AVL",
           "Vehículo":"Vehicle",
           "Fecha Servidor":"Serv Date",
           "Fecha AVL":"AVL Date",
           "RPM":"RPM",
           "Pedal":"Pedal",
           "F. de Carga":"Load F",
           "Potencia":"Power",
           "Estado Motor":"Eng state",
           "Engine Torque Mode ()":"Eng Torque Mode",
           "Actual Percent Torque (%)":"Actual Torque (%)",
           "Actual Speed (RPM)":"ActSpeed (RPM)",
           "Accelerator position (%)":"AccelPosition (%)",
           "Percent Load At Current Speed (%)":"Load at CurrSpeed (%)",
           "Fuel rate (L/h)":"Fuel rate (L/h)",
           "Barometric Pressure (PSI)":"Bar Pressure (PSI)",
           "IMP-LB (PSI)":"IMP-LB (PSI)",
           "IMT-LBF (F)":"IMT-LBF (F)",
           "EGT-AV (F)":"EGT-AV (F)",
           "Battery potential (V)":"Battery pot (V)",
           "Coolant temperature (F)":"Coolant T (F)",
           "Fuel Temperature (F)":"Fuel T (F)",
           "Engine Oil Temperature (F)":"EngOil T (F)",
           "Injector Metering (PSI)":"Inject Met (PSI)",
           "Injector Timing (PSI)":"Inj Timing (PSI)",
           "Pre-filter Oil Pressure (PSI)":"Pre-filtOil Press (PSI)",
           "Instantaneous Estimated Brake Power (HP)":"InstantEst B-Power (HP)",
           "IMT-LBR (F)":"IMT-LBR (F)",
           "IMT-RBF (F)":"IMT-RBF (F)",
           "IMT-RBR (F)":"IMT-RBR (F)",
           "IMP-RB (PSI)":"IMP-RB (PSI)",
           "IMP-RB (MCRS) (PSI)":"IMP-RB (MCRS) (PSI)",
           "Oil Differential Pressure (PSI)":"OilDiff Press (PSI)",
           "Ecu temperature (F)":"Ecu T (F)",
           "EGT-01 (F)":"EGT-01 (F)",
           "EGT-02 (F)":"EGT-02 (F)",
           "EGT-03 (F)":"EGT-03 (F)",
           "EGT-04 (F)":"EGT-04 (F)",
           "EGT-05 (F)":"EGT-05 (F)",
           "EGT-06 (F)":"EGT-06 (F)",
           "EGT-07 (F)":"EGT-07 (F)",
           "EGT-08 (F)":"EGT-08 (F)",
           "EGT-09 (F)":"EGT-09 (F)",
           "EGT-10 (F)":"EGT-10 (F)",
           "EGT-11 (F)":"EGT-11 (F)",
           "EGT-12 (F)":"EGT-12 (F)",
           "EGT-13 (F)":"EGT-13 (F)",
           "EGT-14 (F)":"EGT-14 (F)",
           "EGT-15 (F)":"EGT-15 (F)",
           "EGT-16 (F)":"EGT-16 (F)",
           "Crankcase Pressure (HPI) (in-H2O)":"CC Press (HPI) (in-H2O)",
           "Engine Oil Level (%)":"EngOil Level (%)",
           "Post Oil Filter (PSI)":"PostOil Filt (PSI)",
           "Rifle Oil Pressure (PSI)":"RifleOil Press (PSI)",
           "Coolant Pressure (PSI)":"Coolant Press (PSI)",
           "Ambient Temperature (F)":"Ambient T (F)",
           "EGT-17 (F)":"EGT-17 (F)",
           "EGT-18 (F)":"EGT-18 (F)",
           "IMT-LBM (F)":"IMT-LBM (F)",
           "IMT-RBM (F)":"IMT-RBM (F)",
           "Remote accelerator pedal position (%)":"RemoAccelPedal Pos (%)",
           "Engine Pre-filter Oil Pressure (Extended Range) (PSI)":"EngPre-filterOil Pres (Extended) (PSI)",
           "Post Oil Filter (Extended Range) (PSI)":"PostOilFilt (Extended) (PSI)",
           "Engine Operating State (bit)":"EngOp State (bit)",
           "Engine Turbocharger 1 Compressor Inlet Pressure (kPa)":"EngTcharger 1 CompInlet Press (kPa)",
           "Engine Protection System has Shutdown Engine (bit)":"EngProSyst SD Eng (bit)",
           "Engine Protection System Approaching Shutdown (bit)":"EngProSyst App SD (bit)",
           "Engine Protection System Timer State (bit)":"EngProSys TS (bit)",
           "Engine Oil Filter Differential Pressure (Extended Range) (PSI)":"EngOilFiltDiff Press (Extended) (PSI)",
           "Engine Oil Priming Pump Control (bit)":"EngOilPrPump Control (bit)",
           "Engine Controlled Shutdown Request (bit)":"EngControlled SD Request (bit)",
           "Engine Emergency (Immediate) Shutdown Indication (bit)":"EngE (Immediate) SD Ind (bit)",
           "Power (HP)":"Power (HP)"}

In [11]:
filt_df.rename(columns=newcols, inplace=True)
filt_df.columns.values

array(['ESN', 'AVL', 'Vehicle', 'Serv Date', 'AVL Date', 'RPM', 'Pedal',
       'Load F', 'Power', 'Eng state', 'Eng Torque Mode',
       'Actual Torque (%)', 'ActSpeed (RPM)', 'AccelPosition (%)',
       'Load at CurrSpeed (%)', 'Fuel rate (L/h)', 'Bar Pressure (PSI)',
       'IMP-LB (PSI)', 'IMT-LBF (F)', 'EGT-AV (F)', 'Battery pot (V)',
       'Coolant T (F)', 'Fuel T (F)', 'EngOil T (F)', 'Inject Met (PSI)',
       'Inj Timing (PSI)', 'Pre-filtOil Press (PSI)',
       'InstantEst B-Power (HP)', 'IMT-LBR (F)', 'IMT-RBF (F)',
       'IMT-RBR (F)', 'IMP-RB (PSI)', 'IMP-RB (MCRS) (PSI)',
       'OilDiff Press (PSI)', 'Ecu T (F)', 'EGT-01 (F)', 'EGT-02 (F)',
       'EGT-03 (F)', 'EGT-04 (F)', 'EGT-05 (F)', 'EGT-06 (F)',
       'EGT-07 (F)', 'EGT-08 (F)', 'EGT-09 (F)', 'EGT-10 (F)',
       'EGT-11 (F)', 'EGT-12 (F)', 'EGT-13 (F)', 'EGT-14 (F)',
       'EGT-15 (F)', 'EGT-16 (F)', 'CC Press (HPI) (in-H2O)',
       'EngOil Level (%)', 'PostOil Filt (PSI)', 'RifleOil Press (PSI)',
       'Co

In [7]:
metal_values = pd.read_excel("filtersMetalWeights.xlsx", thousands='.')
metal_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   EQUIPO  15 non-null     int64  
 1   Fe      15 non-null     int64  
 2   Cr      15 non-null     float64
 3   Pb      15 non-null     int64  
 4   Cu      15 non-null     float64
 5   Sn      15 non-null     float64
 6   Al      15 non-null     int64  
 7   Ni      15 non-null     float64
 8   Ag      15 non-null     float64
 9   Si      15 non-null     int64  
 10  B       15 non-null     int64  
 11  Na      15 non-null     int64  
 12  Mg      15 non-null     int64  
 13  Ca      15 non-null     int64  
 14  Ba      15 non-null     int64  
 15  P       15 non-null     int64  
 16  Zn      15 non-null     int64  
 17  Mo      15 non-null     int64  
 18  Ti      15 non-null     int64  
 19  V       15 non-null     int64  
 20  Mn      15 non-null     int64  
 21  K       15 non-null     int64  
 22  Cd  

In [14]:
metal_values

EQUIPO    Fe     Cr    Pb     Cu    Sn   Al   Ni   Ag    Si  ...     Ca  \
0      116  1748   83.0  2026  287.0   5.0  375  0.1  0.1  1004  ...  27366   
1      117  3043  134.0  1419   40.0  29.0  452  0.1  0.1  1611  ...  28764   
2      119  1396   36.0  1822  119.0  31.0  144  0.1  0.1  1280  ...  12517   
3      126   745   23.0  1555    0.1   0.1   61  0.1  0.1  1441  ...  13688   
4      129   981   29.0  1361    0.1  42.0   99  0.1  0.1   363  ...  18223   
5      130  1319    3.0   710    0.1   0.1  133  0.1  0.1  1893  ...  17639   
6      150  1126   28.0   940    0.1   0.1  148  0.1  0.1   650  ...  16836   
7      155   616    1.0    37    0.1   0.1   77  0.1  0.1  1562  ...  10831   
8      161  1119   12.0   808    0.1   0.1  207  0.1  0.1  1823  ...  12516   
9       57  1234   18.0   891    0.1   0.1   56  0.0  0.1   372  ...  17205   
10      64  1256   68.0   783    0.1   0.1  410  0.1  0.1  2229  ...   5225   
11      87   415    0.1  1066    0.1   0.1    0  0.1  0.1   326  ...   3940   
12      88  2338   43.0  1120    0.1   0.1  693  0.0  0.1  2555  ...  19185   
13      94  1215   38.0  1700    0.1  35.0  161  0.1  0.1  1075  ...  29360   
14      97  1420    0.1   361    0.1   0.1    6  0.1  0.1  1733  ...  11294   

    Ba      P     Zn    Mo   Ti  V   Mn    K  Cd  
0    6  19458  31431  1051    0  0    0   84   0  
1   77  22202  39344   991  507  0   15  149   0  
2    3   8742  13761   484    0  0    0  171   0  
3    0  10053  13936   527    0  0    0   54   0  
4    0  11532  19819   832    0  0    0    3   0  
5    0  13469  19612   696    0  0    0   50   0  
6    0  11737  16807   702    0  0    0   31   0  
7    0   6820  12861   380    0  0    0   27   0  
8    0   7781  16692   496    0  0   54   82   0  
9    0  12107  19231   653    0  0    0  229   0  
10   0   3722   9300   149    0  0    0  135   0  
11   0   1441   4945     0    0  0    0    0   0  
12   0  12766  23634   915    0  0  121  335   0  
13   0  17004  24814  1078    0  0    0   48   0  
14   0   8430  14508   586    0  0    0    0   0  

[15 rows x 23 columns]

In [12]:
vehicles = [filt_df.Vehicle.unique()[i] for i in range(15)]

In [37]:
%time colist=[np.hstack([(np.repeat(metal_values.iloc[i,j], np.sum(filt_df.Vehicle == vehicles[i]))) for i in range(metal_values.shape[0])]).flatten() for j in range(metal_values.shape[0])]

Wall time: 13.5 s


In [42]:
colist

[array([116, 116, 116, ...,  97,  97,  97], dtype=int64),
 array([1748, 1748, 1748, ..., 1420, 1420, 1420], dtype=int64),
 array([83. , 83. , 83. , ...,  0.1,  0.1,  0.1]),
 array([2026, 2026, 2026, ...,  361,  361,  361], dtype=int64),
 array([2.87e+02, 2.87e+02, 2.87e+02, ..., 1.00e-01, 1.00e-01, 1.00e-01]),
 array([5. , 5. , 5. , ..., 0.1, 0.1, 0.1]),
 array([375, 375, 375, ...,   6,   6,   6], dtype=int64),
 array([0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1]),
 array([0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1]),
 array([1004, 1004, 1004, ..., 1733, 1733, 1733], dtype=int64),
 array([1167, 1167, 1167, ...,  503,  503,  503], dtype=int64),
 array([1552, 1552, 1552, ...,  315,  315,  315], dtype=int64),
 array([8936, 8936, 8936, ..., 4057, 4057, 4057], dtype=int64),
 array([27366, 27366, 27366, ..., 11294, 11294, 11294], dtype=int64),
 array([6, 6, 6, ..., 0, 0, 0], dtype=int64)]